baseURL = "http://mkar.ch/"
languageCode = "en-us"
title = "Mitchell Karchemsky"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-120199108-1"
relativeURLS=true

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Mitchell Karchemsky, Interaction / Industrial Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "mitch.karchemsky@gmail.com"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Mitchell! I'm a Design Engineer and Software Researcher"
    hero_right = ["My name is Mitchell Karchemsky. I graduated from UC Berkeley, with an undergraduate degree in Cognitive Science, and Computer Science, focusing in Computational Modelling. Currently, I am a Masters Candidate at the UC Berkeley: School of Information in the Information and Data Science program. My interests include Human-Computer Interaction, Embedded Systems, Teaching, and Coffee.", "I served as Research Staff at the Berkeley Institute of Design under Björn Hartmann focusing on HCI topics such as Learning & Expertise Sharing, Interactive Device Design & Fabrication, and Tools for Embedded Systems","I also served as a Design Mentor at the CITRIS Invention Lab, managing digital fabrication equipment as well as mentoring students for embedded systems inventions.", "Currently, I work at Accenture as a Prinicipal Technical Architect focusing on Innovative Products"]
    resume = "ResumeKarchemsky.pdf"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.process]
    enable = true
    title = "Teaching Experience"
    subtitle = "Courses and Mentorship"

[params.footer]
    enable = true
