baseURL = "localhost:1313"
languageCode = "en-us"
title = "Mitchell Karchemsky"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-120199108-1"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Mitchell Karchemsky, Interaction / Industrial Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "mitch.karchemsky@gmail.com"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Mitchell, an Interaction and Industrial Designer from Berkeley."
    hero_right = ["My name is Mitchell Karchemsky. I just graduated from UC Berkeley, studying Cognitive Science, and Computer Science, with a focus in Computational Modelling. My interests include Human-Computer Interaction, Embedded Systems, Teaching, and Coffee.", "I serve as Research Staff at the Berkeley Institute of Design under Björn Hartmann focusing on HCI topics such as Learning & Expertise Sharing, Interactive Device Design & Fabrication, and Tools for Embedded Systems","I currently work at the CITRIS Invention Lab, managing digital fabrication equipment as well as mentoring students for embedded systems inventions."]
    resume = "ResumeKarchemsky.pdf"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.process]
    enable = true
    title = "Teaching Experience"
    subtitle = "Courses and Mentorship"

[params.footer]
    enable = true
